# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Artists seed

Artist.create(name:'Frida Kahlo', biography:'A pintora mexicana espalhou suas imagens ímpares, repletas de cores, pelo mundo. Magdalena Carmen Frida Kahlo y Calderón nasceu no México, filha de pai alemão e mãe espanhola, e se consagrou sobretudo pela composição dos seus autorretratos. Sua vida foi marcada por uma série de desafios - doença de nascença, acidente no bonde, sucessivos abortos, uma relação amorosa conflituosa com Diego Rivera. Mas Frida conseguiu dar a volta por cima e foi capaz de criar obras brilhantes, que entraram para o cânone da pintura ocidental. Os trabalhos de Frida Kahlo, com inspiração surrealista, passaram por várias fases bastante distintas e são de uma riqueza fora da curva.', birthdate:'1907-07-06', deathdate:'1954-07-13', birthplace:'Coyoacán, Distrito Federal, México')
Artist.create(name:'Claude Monet', biography:'O pintor francês considerado um dos maiores nomes do Impressionismo é dos grandes artistas ocidentais. Nascido em Paris no ano de 1840, Claude era filho de um comerciante local e mudou aos cinco anos com a família para a Normandia. A primeira incentivadora do prodígio Monet foi a sua tia, Marie-Jeanne Lacadre, uma amante das belas artes. Aos 15 anos, Claude já vendia caricaturas na cidade onde vivia. Em 1859 Claude Monet se mudou para Paris para desenvolver a carreira artística e, dez anos mais tarde, ao lado do pintor Auguste Renoir, deu o pontapé inicial Movimento Impressionista.', birthdate:'1840-11-14', deathdate:'1926-12-05', birthplace:'Paris, Île-de-France, Reino da França')
Artist.create(name:'Salvador Dalí', biography:'O senhor dos bigodes engraçados foi um dos maiores pintores espanhóis e um dos grandes representantes do Surrealismo. Nascido em Girona, Salvador Domingo Dalí Domènech era filho de um tabelião e sempre teve uma personalidade fora do comum. Em 1922, quando se mudou para Madrid, entrou para a Academia de Belas Artes de San Fernando e ganhou dois grandes amigos: o poeta Federico Garcia Lorca e o cineasta Luís Bunuel. Autêntico, desde cedo Dalí usava roupas excêntricas e usava cortes de cabelo e barba que o tornavam uma pessoa especial. Em 1925 o artista fez a sua primeira mostra individual em Barcelona e daquele momento em diante foi só cada vez mais apurando a sua arte singular.', birthdate:'1904-05-11', deathdate:'1989-01-23', birthplace:'Figueres, Espanha')