# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Styles seed
Style.create(title: 'Abstrata', description: "Pinturas abstratas são de arte que não tem referência a nenhuma realidade figurativa, é a arte que retrata formas reais de maneira simplificada ou reduzida, mantendo apenas uma alusão ao sujeito natural original. A arte abstrata não é uma invenção do século XX, nas religiões judaica e islâmica, a representação dos seres humanos não era permitida, portanto, as culturas islâmica e judaica desenvolveram um alto padrão de artes decorativas.")
Style.create(title: 'Art Nouveau', description: "O Art Nouveau ou Arte Nova foi um movimento artístico que surgiu no final do século XIX na Bélgica, é um estilo de arte decorativa elegante, caracterizado por padrões intricados de linhas curvas, fora do contexto em que normalmente surgem as vanguardas artísticas. Vigorou entre 1880 e 1920, aproximadamente. Existia na sociedade em geral o desejo de buscar um estilo que refletisse e acompanhasse as inovações da sociedade industrial. Art Nouveau permaneceu popular até por volta da época da Primeira Guerra Mundial, e foi finalmente substituído pelo estilo Art Deco.")
Style.create(title: 'Classicista', description: "O termo clássico entrou em uso no século XVII para descrever as artes e a cultura das antigas civilizações da Grécia e de Roma. O seguimento dos princípios dessas antigas civilizações na arte, arquitetura e literatura é chamado de classicismo.\nO classicismo é geralmente associado à harmonia e contenção e obediência a padrões reconhecidos de forma e habilidade.\nA partir da Renascença, o classicismo dominou a arte ocidental, com a mitologia clássica - consistindo nos vários mitos e lendas dos antigos deuses e heróis gregos e romanos - tornando-se uma importante fonte de assunto para a pintura histórica.")
Style.create(title: 'Cubista', description: "O cubismo abriu quase infinitas novas possibilidades para o tratamento da realidade visual na arte e foi o ponto de partida para muitos estilos abstratos posteriores, incluindo o construtivismo e o neoplasticismo.\nAo quebrar objetos e figuras em áreas distintas - ou planos -, os artistas pretendiam mostrar diferentes pontos de vista ao mesmo tempo e dentro do mesmo espaço e, assim, sugerir sua forma tridimensional. Ao fazê-lo, eles também enfatizaram a planicidade bidimensional da tela, em vez de criar a ilusão de profundidade. Isso marcou uma ruptura revolucionária com a tradição européia de criar a ilusão do espaço real a partir de um ponto de vista fixo usando dispositivos como a perspectiva linear, que havia dominado a representação da Renascença em diante.")
Style.create(title: 'Expressionista', description: "O expressionismo é um estilo de arte em que a intenção não é reproduzir com precisão um sujeito, mas retratá-lo de modo a expressar o estado interior do artista. O movimento foi iniciado na Alemanha, e foi influenciado por estilos emocionalmente carregados como Simbolismo, Fauvismo e Cubismo. Expressionistas Líderes incluíram Wassily Kandinsky, Franz Marc, George Grosz e Amadeo Modigliani. Existem vários grupos diferentes e um tanto sobrepostos de artistas expressionistas, incluindo Der Blaue Reiter, Die Brücke, Die Neue Sachlichkeit e a Escola Bauhaus. Em meados do século XX, o Expressionismo Abstrato (no qual não há assunto, mas pura forma abstrata) desenvolveu-se num estilo extremamente influente nos Estados Unidos.")
Style.create(title: 'Figurativa', description: "Arte figurativa descreve pinturas que são claramente derivadas de fontes de objetos reais e, portanto, são por definição representacionais. O termo \"arte figurativa\" é frequentemente entendido como arte que representa a figura humana. Os elementos formais, aqueles efeitos estéticos criados pelo design, dos quais depende a arte figurativa, incluem linha, forma, cor, luz e escuridão, massa, volume, textura e perspectiva.")
Style.create(title: 'Fotorrealista', description: "Fotorrealismo, também chamado de super-realismo, movimento artístico americano que começou nos anos 1960, tomando a fotografia como sua inspiração. Pintores foto-realistas criaram imagens altamente ilusionistas que não se referiam à natureza, mas à imagem reproduzida.")
Style.create(title: 'Impressionista', description: "O impressionismo foi desenvolvido por Claude Monet e outros artistas sediados em Paris desde o início da década de 1860. (Embora se possa dizer que o processo de pintar no local foi pioneiro na Grã-Bretanha por John Constable, por volta de 1813-17, por meio de seu desejo de pintar a natureza de maneira realista).\nEm vez de pintar em um estúdio, os impressionistas descobriram que podiam capturar os efeitos momentâneos e transitórios da luz solar trabalhando rapidamente, diante de seus súditos, ao ar livre (en plein air) e não em um estúdio. Isso resultou em uma maior consciência da luz e cor e o padrão de mudança da cena natural. A pincelada tornou-se rápida e quebrou-se em salpicos separados, a fim de tornar a qualidade da luz passageira.")
Style.create(title: 'Realista', description: "Artistas realistas representam personagens cotidianos, situações, dilemas e objetos, tudo de uma maneira \"realista\". O realismo era contra o romantismo, um gênero que dominava a arte francesa no final do século XVIII e início do século XIX. Não distorcida pelo preconceito pessoal, o Realismo acreditava na ideologia da realidade objetiva e se revoltava contra o emocionalismo exagerado. Verdade e exatidão tornaram-se os objetivos em muitas pinturas realistas.")
Style.create(title: 'Rococó', description: "As pinturas rococó mantinham o gosto barroco por formas complexas e padrões intricados e integravam uma variedade de características diversas, incluindo o gosto por desenhos orientais e composições assimétricas. Na prática Rococó é um estilo de curvas curtas, voltas e contra-curvas, muitas vezes elaboradas com fantasia. Na arte, a beleza, a sensualidade, a curvatura e a sensualidade rococó são exemplificadas nos trabalhos de François Boucher, Jean-Honoré Fragonard e Jean-Antoine Watteau e na escultura de Clodion.")
Style.create(title: 'Simbolista', description: "O simbolismo é um movimento do século XIX no qual a arte foi infundida com uma sensibilidade exagerada e um assustador misticismo. O simbolismo retrata a mitologia e a imaginação onírica para uma linguagem visual da alma. Mais uma abordagem filosófica do que um estilo real de arte e uma continuação do Tradição romântica. Os artistas mais conhecidos são John Henry Fuseli e Caspar David Friedrich, Gustave Moreau, Puvis de Chavannes e Odilon Redon.")
Style.create(title: 'Surrealista', description: "O surrealismo visava revolucionar a experiência humana, rejeitando uma visão racional da vida em favor de uma que afirmava o valor do inconsciente e dos sonhos. Os poetas e artistas do movimento encontraram magia e beleza estranha no inesperado e no estranho, no desconsiderado e no não convencional. Embora \"surreal\" seja frequentemente usado livremente para significar simplesmente \"estranho\" ou \"onírico\", não deve ser confundido com \"surrealista\", que descreve uma conexão substancial com a filosofia e as manifestações do movimento surrealista.")
Style.create(title: 'Veduta', description: "A veduta (italiano para \"visão\"; plural: vedute) é uma pintura altamente detalhada, geralmente em larga escala ou, mais frequentemente impressa, de uma paisagem urbana ou alguma outra vista. Os pintores de vedute são referidos como vedutisti.")
